// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: Readonly<React.ReactNode>;
}

export default async function RootLayout({ children }: RootLayoutProps) {
  const session = await auth(); // Récupère la session côté serveur

  return (
    // Enveloppez l'application avec le SessionProvider
    <SessionProvider session={session}>
      <html lang="fr">
        <body className={inter.className}>{children}</body>
      </html>
    </SessionProvider>
  );
}
